### ISSUE TITLE
sqlite3InitModule always take 3s to finish

### ISSUE THREAD

**Issue by terry-fei** [tomayac/sqlite-wasm#33] opened 2023-08-23 19:47 UTC
I use SQLite WASM in a worker with OPFS. However, I have noticed that when I refresh the page, the initialization time varies - sometimes it takes around 30ms, while other times it takes around 3 seconds.

`sqlite sqlite3InitModule use 3076.3900000452995ms`

**Comment by tomayac** [comment] 2023-08-24 10:34
Do you have a URL for us to look at? @sgbeal, is this something you have heard before?

**Comment by sgbeal** [comment] 2023-08-24 12:39
i unfortunately have no suggestions. It's not a behavior i've noticed in many thousands of test runs.

There's no 3-second timeout anywhere in the library. There is  4-second timeout on loading the OPFS async proxy worker, but otherwise no timeouts. Waiting on that file necessarily delays initialization on OPFS-capable environments, but it is rare to have a significant load-delay, and certainly not a predictably regular one, with that file so i'm suspecting that that's not the cause for the delay.

**Comment by terry-fei** [comment] 2023-08-24 17:38
The delay only occurs when refreshing the page, and it works fine during the initial loading.

**Comment by terry-fei** [comment] 2023-08-24 17:46
<img width="739" alt="image" src="https://github.com/tomayac/sqlite-wasm/assets/4183342/57043b6d-1b0c-4e66-b832-aa272789f5da">
I think i fine the problem

**Comment by terry-fei** [comment] 2023-08-24 18:18
Is there anything I can do to avoid this issue? The code runs in an offscreen document within a Chrome extension, and it significantly hampers the development experience.

**Comment by sgbeal** [comment] 2023-08-24 22:52
i haven't seen it happen in 6+ months and had forgotten all about it. i don't know that i ever found a reliable workaround but it eventually just stopped happening, or only happening for so short a time as to go unnoticed, some time in the past 6-8 months or so.

This is untested, but perhaps tapping reload twice quickly in a row will give the browser the couple of milliseconds it needs to get the handles closed before the new tab tries to open them. It would be a stupid workaround, certainly, but it might work.

To be clear: this isn't a bug in the library, it's the browser doing things out of order: giving a new tab OPFS access to files while a closed tab still has locked handles to free. To the library that's indistinguishable from any other reason for contention so it cannot transparently account for this quirk.

**Comment by tomayac** [comment] 2023-08-25 06:53
Thanks for the investigation! If there's a way to reliably reproduce the problem, please file a [new Chromium bug](https://new.crbug.com/). Closing the issue here then.

**Closed by tomayac** 2023-08-25 06:53 UTC
